/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      colors: {
        'surface-container-lowest': '#ffffff',
        'surface-tint': '#5e5e5e',
        'on-tertiary-fixed-variant': '#474747',
        outline: '#737786',
        'surface-container': '#eeeeee',
        'on-error-container': '#93000a',
        tertiary: '#5c5c5c',
        'on-surface-variant': '#424654',
        'on-tertiary-container': '#fdfdfd',
        'primary-fixed-dim': '#c6c6c6',
        'on-background': '#1a1c1c',
        'surface-dim': '#dadada',
        'on-secondary': '#ffffff',
        background: '#f9f9f9',
        'tertiary-fixed': '#e2e2e2',
        surface: '#f9f9f9',
        'tertiary-container': '#757575',
        'on-primary-fixed': '#1b1b1b',
        'tertiary-fixed-dim': '#c6c6c6',
        'on-secondary-fixed': '#001947',
        'surface-container-low': '#f4f3f3',
        'on-tertiary-fixed': '#1b1b1b',
        'surface-container-highest': '#e2e2e2',
        'on-secondary-fixed-variant': '#00419f',
        'inverse-on-surface': '#f1f1f1',
        'inverse-primary': '#c6c6c6',
        'inverse-surface': '#2f3131',
        'surface-container-high': '#e8e8e8',
        'on-secondary-container': '#fefcff',
        'secondary-fixed-dim': '#b1c5ff',
        'on-primary-fixed-variant': '#474747',
        'on-tertiary': '#ffffff',
        'on-primary-container': '#fefefe',
        'surface-bright': '#f9f9f9',
        'primary-fixed': '#e2e2e2',
        'on-primary': '#ffffff',
        'on-error': '#ffffff',
        secondary: '#276EF1',
        'primary-container': '#757575',
        'on-surface': '#1a1c1c',
        'surface-variant': '#e2e2e2',
        'error-container': '#ffdad6',
        'secondary-fixed': '#dae2ff',
        error: '#ba1a1a',
        'outline-variant': '#c2c6d7',
        'secondary-container': '#256df0',
        primary: '#5d5d5d',
      },
    },
  },
  plugins: [],
};
